#!/bin/sh

active=$(
  gdbus call --session \
    --dest org.gnome.Shell \
    --object-path /org/gnome/Shell \
    --method org.freedesktop.DBus.Properties.Get \
    org.gnome.Shell OverviewActive |
  grep -o 'true\|false'
)

if [ "$active" = "true" ]; then
  next=false
else
  next=true
fi

gdbus call --session \
  --dest org.gnome.Shell \
  --object-path /org/gnome/Shell \
  --method org.freedesktop.DBus.Properties.Set \
  org.gnome.Shell OverviewActive "<$next>" >/dev/null
