#!/bin/bash
# Switch GNOME input source to US keyboard when tmux pane focus changes.
# Requires focus-us-input@local GNOME extension to be enabled.
gdbus call --session \
    --dest org.gnome.Shell.Extensions.FocusUsInput \
    --object-path /org/gnome/Shell/Extensions/FocusUsInput \
    --method org.gnome.Shell.Extensions.FocusUsInput.SwitchToUs \
    >/dev/null 2>&1
