#!/bin/bash
# Switch GNOME input source to US keyboard when tmux pane focus changes.
# Requires fep-switcher@local GNOME extension to be enabled.
gdbus call --session \
    --dest org.gnome.Shell.Extensions.FepSwitcher \
    --object-path /org/gnome/Shell/Extensions/FepSwitcher \
    --method org.gnome.Shell.Extensions.FepSwitcher.SwitchToUs \
    >/dev/null 2>&1
